# NumPy Tutorial
__By Anish Sachdeva__

In [2]:
# pip install numpy
import numpy as np

## The Basics

In [3]:
a = [1, 2, 3]
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>


In [4]:
a = np.array(a)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# We can also create arrays of different dimensions in numpy
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
# we can see the dimension of any numpy array using the .shape command
print(b.shape)

(2, 3)


In [8]:
a = np.array([1, 2, 3])
print(a.shape)

(3,)


## Creating arrays using `Numpy.random` package

In [25]:
np.random.seed(10)
r = np.random.randint(100, size=(4, 10))
print(r)

[[ 9 15 64 28 89 93 29  8 73  0]
 [40 36 16 11 54 88 62 33 72 78]
 [49 51 54 77 69 13 25 13 92 86]
 [30 30 89 12 65 31 57 36 27 18]]


In [26]:
r2 = np.random.rand(3, 4)
print(r2)

[[0.05644419 0.76545582 0.01178803 0.61194334]
 [0.33188226 0.55964837 0.33549965 0.41118255]
 [0.0768555  0.85304299 0.43998746 0.12195415]]


## Accessing Specific Elements

In [27]:
r = np.random.randint(10, size=(3, 4))
print(r)

[[4 0 8 5]
 [4 7 8 8]
 [2 6 2 8]]


In [28]:
# accessing first row
print(r[0, :])

[4 0 8 5]


In [29]:
# accessing last row
print(r[-1, :])

[2 6 2 8]


In [30]:
# accessing specific row
row = 2
print(r[row - 1, ])

[4 7 8 8]


In [32]:
# accessing the first column
print(r[:, 0])

(3,)


In [33]:
# accessing the first column and reshaping it into a column vector
c1 = r[:, 0]
print(c1)
c1 = c1.reshape((3, 1))
print(c1)

[4 4 2]
[[4]
 [4]
 [2]]


In [34]:
# accessing the last column
c2 = r[:, -1]
print(c2)

[5 8 8]


In [35]:
# reshaping the last column into column vector
c2 = c2.reshape((3, 1))
print(c2)

[[5]
 [8]
 [8]]


In [36]:
# retreiving specific rows
np.random.seed(10)
r = np.random.randint(low=0, high=100, size=(5, 6))
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [39]:
print(r[[0, 1], :])

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]]


In [40]:
# printing selected rows
print(r[[0, 3], ])

[[ 9 15 64 28 89 93]
 [72 78 49 51 54 77]]


In [41]:
# changing order of rows
print(r[[3, 0, 4], ])

[[72 78 49 51 54 77]
 [ 9 15 64 28 89 93]
 [69 13 25 13 92 86]]


In [42]:
# getting specific columns
print(r[:, [4, 2]])

[[89 64]
 [40 73]
 [62 54]
 [54 49]
 [92 25]]


In [43]:
# selecting a specific element (row, column)
print(r[0, 0])

9


In [44]:
row, column = 2, 3
print(r[row, column])

88


Getting elements using start, stop, step size (getting crazy 🙃) 

In [45]:
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [46]:
print(r[::2, :])

[[ 9 15 64 28 89 93]
 [16 11 54 88 62 33]
 [69 13 25 13 92 86]]


In [47]:
print(r[::-1, ])

[[69 13 25 13 92 86]
 [72 78 49 51 54 77]
 [16 11 54 88 62 33]
 [29  8 73  0 40 36]
 [ 9 15 64 28 89 93]]


In [70]:
print(r[::-1, ::-1])

[[86 92 13 25 13 69]
 [77 54 51 49 78 72]
 [33 62 88 54 11 16]
 [36 40  0 73  8 29]
 [93 89 28 64 15  9]]


In [48]:
print(r[1:4:2, 0:5:3])
# 1, 3  |  0, 3

[[29  0]
 [72 51]]


## Changing the Value of the matrices

In [49]:
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [50]:
#changing the value of a single element
r[0, 0] = 100
print(r)

[[100  15  64  28  89  93]
 [ 29   8  73   0  40  36]
 [ 16  11  54  88  62  33]
 [ 72  78  49  51  54  77]
 [ 69  13  25  13  92  86]]


In [53]:
r[0, :]

array([100,  15,  64,  28,  89,  93])

In [58]:
# changing the value of an entire row
r[0, :] = np.random.randint(low=-100, high=0, size=(1, 6))
print(r)

[[-12 -89 -83 -54 -93 -25]
 [ 29   8  73   0  40  36]
 [ 16  11  54  88  62  33]
 [ 72  78  49  51  54  77]
 [ 69  13  25  13  92  86]]


In [59]:
r[:, 2]

array([-83,  73,  54,  49,  25])

In [63]:
# changing the value of an entire column 
r[:, 2] = np.random.randint(low=-200, high=-100, size=(5,))
print(r)

[[ -12  -89 -123  -54  -93  -25]
 [  29    8 -112    0   40   36]
 [  16   11 -185   88   62   33]
 [  72   78 -194   51   54   77]
 [  69   13 -115   13   92   86]]


In [65]:
# changing the value of some particular elements
r[1, [0, 2]] = 100
print(r)

[[ -12  -89 -123  -54  -93  -25]
 [ 100    8  100    0   40   36]
 [  16   11 -185   88   62   33]
 [  72   78 -194   51   54   77]
 [  69   13 -115   13   92   86]]


In [66]:
k = r.copy()
k

array([[ -12,  -89, -123,  -54,  -93,  -25],
       [ 100,    8,  100,    0,   40,   36],
       [  16,   11, -185,   88,   62,   33],
       [  72,   78, -194,   51,   54,   77],
       [  69,   13, -115,   13,   92,   86]])

In [67]:
# broadcasting
k[0, :] = 100
k

array([[ 100,  100,  100,  100,  100,  100],
       [ 100,    8,  100,    0,   40,   36],
       [  16,   11, -185,   88,   62,   33],
       [  72,   78, -194,   51,   54,   77],
       [  69,   13, -115,   13,   92,   86]])

In [69]:
k[:, 0] = -100
k

array([[-100,  100,  100,  100,  100,  100],
       [-100,    8,  100,    0,   40,   36],
       [-100,   11, -185,   88,   62,   33],
       [-100,   78, -194,   51,   54,   77],
       [-100,   13, -115,   13,   92,   86]])

In [70]:
k[1:4:2, [0, 4]] = -50
k

array([[-100,  100,  100,  100,  100,  100],
       [ -50,    8,  100,    0,  -50,   36],
       [-100,   11, -185,   88,   62,   33],
       [ -50,   78, -194,   51,  -50,   77],
       [-100,   13, -115,   13,   92,   86]])

In [71]:
k[0:3:2, [3, 4]]

array([[100, 100],
       [ 88,  62]])

## Different Initialization Methods

In [72]:
# Creating the zeros Matrix
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
z = np.zeros((3, 4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [76]:
z.dtype

dtype('float64')

In [74]:
# creating matrix with data type defined as int
z = np.zeros((3, 4), dtype=np.int)
print(z)
print(z.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [77]:
# creating all 1's matrix
o = np.ones((2, 4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [78]:
o = np.ones((2, 4), dtype=np.int)
print(o)

[[1 1 1 1]
 [1 1 1 1]]


In [81]:
# creating a matrix with some arbitrary number
f = np.full(shape=(3, 4), fill_value=90)
print(f)
print(f.dtype)

[[90 90 90 90]
 [90 90 90 90]
 [90 90 90 90]]
int32


In [82]:
f = np.full(shape=(1, 2), fill_value=2.0)
print(f)
print(f.dtype)

[[2. 2.]]
float64


In [83]:
# The Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.identity(5, dtype=np.int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [85]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Creating copy of Arrays

In [86]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [87]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Broadcasting in NumPy Arrays

In [88]:
a = [1, 2, 3]
print(type(a))
print(a + 1)

<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [89]:
a = np.array([1, 2, 3])
a + 1

array([2, 3, 4])

In [92]:
np.random.randint(low=0, high=100, size=(4, 5)) - 50

array([[-20,  31, -33, -34, -50],
       [-19,  23,  14, -12, -28],
       [ 46,  16,  17,  12,  45],
       [ 49, -23,  32,  12,  27]])

## Basic Mathematical Operations 

In [93]:
# Multilication with scalar
np.random.seed(10)
A = np.random.randint(0, 100, size=(3, 4))
print(A)

[[ 9 15 64 28]
 [89 93 29  8]
 [73  0 40 36]]


In [94]:
A * 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [95]:
4 * A

array([[ 36,  60, 256, 112],
       [356, 372, 116,  32],
       [292,   0, 160, 144]])

In [96]:
# Division with scalar
A / 2

array([[ 4.5,  7.5, 32. , 14. ],
       [44.5, 46.5, 14.5,  4. ],
       [36.5,  0. , 20. , 18. ]])

In [97]:
A // 3

array([[ 3,  5, 21,  9],
       [29, 31,  9,  2],
       [24,  0, 13, 12]], dtype=int32)

In [102]:
A / np.array([1, 2, 3, 4])

array([[ 9.        ,  7.5       , 21.33333333,  7.        ],
       [89.        , 46.5       ,  9.66666667,  2.        ],
       [73.        ,  0.        , 13.33333333,  9.        ]])

In [98]:
B = np.random.randint(1, 5, size=(3, 4))
B

array([[4, 1, 1, 4],
       [4, 3, 1, 4],
       [3, 3, 2, 1]])

In [99]:
A

array([[ 9, 15, 64, 28],
       [89, 93, 29,  8],
       [73,  0, 40, 36]])

In [100]:
A / B

array([[ 2.25      , 15.        , 64.        ,  7.        ],
       [22.25      , 31.        , 29.        ,  2.        ],
       [24.33333333,  0.        , 20.        , 36.        ]])

In [104]:
A / np.random.randint(1, 5, size=(3, 4))

array([[ 3.        , 15.        , 21.33333333,  7.        ],
       [89.        , 23.25      , 14.5       ,  2.66666667],
       [18.25      ,  0.        , 40.        , 18.        ]])

## Matrix Operations

In [105]:
type(A)

numpy.ndarray

In [106]:
A = np.random.randint(1, 20, size=(2, 3))
print(A)

[[ 1 13  6]
 [ 5  8 19]]


In [107]:
B = np.random.randint(1, 20, size=(2, 3))
print(B)

[[13  3  9]
 [16 14 16]]


In [108]:
A + B

array([[14, 16, 15],
       [21, 22, 35]])

In [109]:
A + 2 * B

array([[27, 19, 24],
       [37, 36, 51]])

In [110]:
A - B

array([[-12,  10,  -3],
       [-11,  -6,   3]])

## Element wise Operations

In [111]:
print(A)

[[ 1 13  6]
 [ 5  8 19]]


In [112]:
# element wise power operator
A ** 2

array([[  1, 169,  36],
       [ 25,  64, 361]], dtype=int32)

In [113]:
np.sin(A)

array([[ 0.84147098,  0.42016704, -0.2794155 ],
       [-0.95892427,  0.98935825,  0.14987721]])

In [114]:
import math
math.sin(A)

TypeError: only size-1 arrays can be converted to Python scalars

In [115]:
np.cos(A)

array([[ 0.54030231,  0.90744678,  0.96017029],
       [ 0.28366219, -0.14550003,  0.98870462]])

In [116]:
np.tan(A)

array([[ 1.55740772,  0.46302113, -0.29100619],
       [-3.38051501, -6.79971146,  0.15158947]])

In [117]:
np.exp(A)

array([[2.71828183e+00, 4.42413392e+05, 4.03428793e+02],
       [1.48413159e+02, 2.98095799e+03, 1.78482301e+08]])

## Linear Algebra

In [118]:
# Taking the matrix dot products between 2 matrices
A = np.array([[1, 2]])
B = np.array([[5, 10, 0], [-9, 0, 3]])

In [119]:
print(A)

[[1 2]]


In [120]:
print(B)

[[ 5 10  0]
 [-9  0  3]]


In [121]:
A.shape

(1, 2)

In [122]:
B.shape

(2, 3)

In [124]:
# -13 10 6
R = A.dot(B)
print(R)

[[-13  10   6]]


In [125]:
R.shape

(1, 3)

## Important

$dim A$ = ($n_1$, $m_1$)

$dim B$ = ($n_2$, $m_2$)

if $m_1 = n_2$

$$(n_1, m_2)$$

In [126]:
print(A.shape)
print(B.shape)
print(R.shape)

(1, 2)
(2, 3)
(1, 3)


In [127]:
# Determinant of a Square Matrix
A = np.random.randint(-100, 100, size=(4, 4))
print(A)

[[ 34 -15  50 -89]
 [ 12 -88 -38  85]
 [-21   8 -58 -43]
 [ -3 -50 -55  68]]


In [128]:
print(np.linalg.det(A))

3610545.0000000047


In [129]:
I = np.identity(4, dtype=np.int)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [130]:
print(np.linalg.det(I))

1.0


In [131]:
# Find the Trace of a Square Matrix
print(A)

[[ 34 -15  50 -89]
 [ 12 -88 -38  85]
 [-21   8 -58 -43]
 [ -3 -50 -55  68]]


In [132]:
print(np.trace(A))

-44


In [133]:
print(np.trace(I))

4


In [134]:
# calculating the inverse of a matrix
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [135]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.05823608 -0.13078219 -0.05714511  0.20356262]
 [ 0.01426073 -0.0620308  -0.02393821  0.08106588]
 [-0.01800227  0.04806615  0.00941825 -0.07768883]
 [-0.00150559 -0.01250365 -0.01250504  0.0204573 ]]


In [199]:
K = np.arange(9).reshape(3, 3)
K

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [200]:
np.linalg.det(K)

0.0

In [201]:
np.linalg.inv(K)

LinAlgError: Singular matrix

In [136]:
print(A.dot(A_inv))

[[ 1.00000000e+00  9.17668719e-16 -9.36750677e-17 -4.40619763e-16]
 [ 2.34187669e-17  1.00000000e+00 -3.92047506e-16  5.65519853e-16]
 [ 2.34187669e-17 -5.22151766e-16  1.00000000e+00  1.21430643e-16]
 [-7.28583860e-17  4.85722573e-17 -1.80411242e-16  1.00000000e+00]]


In [137]:
print(A_inv.dot(A))

[[ 1.00000000e+00 -2.77555756e-16  5.82867088e-16  1.44328993e-15]
 [-3.60822483e-16  1.00000000e+00  3.33066907e-16  4.44089210e-16]
 [ 2.08166817e-16 -1.38777878e-16  1.00000000e+00 -1.05471187e-15]
 [-1.00613962e-16  6.93889390e-18  5.20417043e-17  1.00000000e+00]]


In [139]:
J = A.dot(A_inv)
print(J)

[[ 1.00000000e+00  9.17668719e-16 -9.36750677e-17 -4.40619763e-16]
 [ 2.34187669e-17  1.00000000e+00 -3.92047506e-16  5.65519853e-16]
 [ 2.34187669e-17 -5.22151766e-16  1.00000000e+00  1.21430643e-16]
 [-7.28583860e-17  4.85722573e-17 -1.80411242e-16  1.00000000e+00]]


In [185]:
mask = np.array(J > 10 ** -10, dtype=np.int)
mask

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [187]:
mask2 = np.array([
    [1, 1, 1, 1],
    [0, 0, 0, 0],
    [0.5, 0.5, 0.5, 0.5],
    [0, 0, 0, 0]
])
mask2

array([[1. , 1. , 1. , 1. ],
       [0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5],
       [0. , 0. , 0. , 0. ]])

In [189]:
A * mask2

array([[ 50. ,  51. ,  -6. ,  39. ],
       [  0. ,  -0. ,   0. ,  -0. ],
       [-41. ,   9. , -14.5,  -6. ],
       [  0. ,   0. ,   0. ,   0. ]])

In [186]:
mask * J

array([[ 1., -0., -0., -0.],
       [ 0.,  1., -0., -0.],
       [ 0., -0.,  1., -0.],
       [-0., -0.,  0.,  1.]])

In [193]:
# thresholding
mask_3 = np.array(A > 10, dtype=np.int)
mask_3

array([[1, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 1, 1, 1]])

In [194]:
A * mask_3

array([[50, 51,  0, 39],
       [56,  0, 37,  0],
       [ 0, 18,  0,  0],
       [39, 45, 74, 35]])

In [195]:
# finding the transpose of a matrix
B = np.arange(6).reshape(2, 3)
print(B)

[[0 1 2]
 [3 4 5]]


In [196]:
print(B.shape)

(2, 3)


In [198]:
print(B.T)
print(B.T.shape)

[[0 3]
 [1 4]
 [2 5]]
(3, 2)


In [202]:
J = np.array([[1, 2,3, 4, 5]])
J

array([[1, 2, 3, 4, 5]])

In [203]:
J.shape

(1, 5)

In [206]:
J.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

## Statistics

In [207]:
print(A)

[[ 50  51  -6  39]
 [ 56 -26  37 -85]
 [-82  18 -29 -12]
 [ 39  45  74  35]]


In [209]:
# finding minimum in the matrix
np.min(A)

-85

In [210]:
# finding minimum in every column vector
np.min(A, axis=0)

array([-82, -26, -29, -85])

In [211]:
# finding the mimimum in every row vector
np.min(A, axis=1)

array([ -6, -85, -82,  35])

In [212]:
# finding maximum in entire matrix
print(np.max(A))

74


In [213]:
# finding maximum in every column vector 
np.max(A, axis=0)

array([56, 51, 74, 39])

In [158]:
# finding the maximum in every row vector
np.max(A, axis=1)

array([12, 85, -3, 68])

In [215]:
# sum of every element in the matrix
np.sum(A)

204

In [217]:
# sum of elements in every column vector
np.sum(A, axis=0)

array([ 63,  88,  76, -23])

In [218]:
# sum of elements in every row vector
np.sum(A, axis=1)

204

In [224]:
A.sum(axis=1)

array([ 134,  -18, -105,  193])

## Boolean Operations on Arrays

In [225]:
A = np.arange(35).reshape(5, 7)
print(A)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [226]:
# equality check
A == 4

array([[False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [227]:
# comparison operator
A < 10

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [228]:
A >= 23

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [229]:
# converting a boolean array to integer array
(A < 20).astype(np.int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])